### ISSUE TITLE
No normalization of add/remove/toggle in IE10 and IE11

### ISSUE THREAD

**Issue by mhubenthal** [yola/classlist-polyfill#2]
This is a bug carried over from the eligrey/classList.js repository. Here's a good summary of the issue: https://github.com/eligrey/classList.js/issues/44

**Comment by beck** [comment]
This should be fixed: https://github.com/eligrey/classList.js/pull/57

And is published: https://github.com/yola/classlist-polyfill/releases/tag/1.2.0
